# Numpy Basic functions

In [1]:
import numpy as np
array1=np.array([[2,0,4,5,6],[4,5,6,0,12]]) # make sure there are equal number of coloumns
print (array1)
array2=np.array([[2,3.5,4,0.5,6.9],[4,5,6,7.45,8]],dtype='int32') # forcing numpy to change the data type for floats to int
#print (type(array1))
array3=np.array([[2,1,4,5,6],[4,5,6,4,12]])

[[ 2  0  4  5  6]
 [ 4  5  6  0 12]]


In [2]:
array1[0,4] #zeroth row fourth column


6

In [3]:
array1[1,4]  #first row fourth column

12

In [4]:
array1[0,0]

2

In [5]:
array1[1,0]

4

In [6]:
array1.shape

(2, 5)

In [7]:
array1.dtype

dtype('int32')

In [8]:
array2.dtype

dtype('int32')

In [9]:
np.zeros(4)

array([0., 0., 0., 0.])

In [10]:
# np.zeros([4,6])
np.zeros([4,6],dtype='int32') # forcing integer output

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [11]:
np.zeros((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [12]:
np.ones((6)).dtype #returns data type

dtype('float64')

In [13]:
np.ones((6))

array([1., 1., 1., 1., 1., 1.])

In [14]:
np.empty((4,6)) # np.empty may look similar to np.zero but it is not. It just allocates the empty cells not necessarily being zero.

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [15]:
array1

array([[ 2,  0,  4,  5,  6],
       [ 4,  5,  6,  0, 12]])

In [16]:
array1*array1

array([[  4,   0,  16,  25,  36],
       [ 16,  25,  36,   0, 144]])

In [17]:
array1/array1

C:\Users\DELL\AppData\Local\Temp\ipykernel_5772\3963778006.py:1: RuntimeWarning: invalid value encountered in true_divide
  array1/array1


array([[ 1., nan,  1.,  1.,  1.],
       [ 1.,  1.,  1., nan,  1.]])

In [18]:
array1

array([[ 2,  0,  4,  5,  6],
       [ 4,  5,  6,  0, 12]])

In [19]:
array1**array1 # displays wrong value for 12 also called as garbage value.

array([[         4,          1,        256,       3125,      46656],
       [       256,       3125,      46656,          1, -251658240]],
      dtype=int32)

In [20]:
12**12 # correct value for 12^12

8916100448256

In [21]:
np.array((12**12))# here data type changed to int64 for output as it is a larger number. python int too large error.

array(8916100448256, dtype=int64)

In [22]:
np.array((12.0**12),dtype= 'int32')# here data type forced changed to int32 giving decimal as i/p while int32 being to small to handle  .
# np.array((12**12),dtype= 'int32')

OverflowError: Python int too large to convert to C long

In [23]:
np.array((12.0**12)).dtype #checking the type for decimal 

dtype('float64')

In [24]:
np.array((12.0**12)) # displays correct value 

array(8.91610045e+12)

In [25]:
1/array3

array([[0.5       , 1.        , 0.25      , 0.2       , 0.16666667],
       [0.25      , 0.2       , 0.16666667, 0.25      , 0.08333333]])

# Slicing Arrays

In [26]:
array1

array([[ 2,  0,  4,  5,  6],
       [ 4,  5,  6,  0, 12]])

In [27]:
# array1[0] # prints the first list with index 0 [[this],[]]
# array1[1] # prints the second list with index 1 [[],[this]]
# array1[0:1] # prints the first list with index 0:1 [[this],[]] always prints 1 less -->if 1 prints 0
array1[0:2] # prints the list with index 0:2 [[this],[this]] always prints 1 less--> if 2 prints 1

array([[ 2,  0,  4,  5,  6],
       [ 4,  5,  6,  0, 12]])

In [28]:
array4=np.array([2,0,4,5,6,8,9])

In [29]:
array4[4:6]  #slicing array

array([6, 8])

In [30]:
a=array4[4:6] #assigning integer to array. To avoid changing the index of parent array use below code
# a=array4[4:6].copy()

In [31]:
a # integer print

array([6, 8])

In [32]:
a[0]=10 # changing value at index 0

In [33]:
a

array([10,  8])

In [34]:
array4 # array4 index at array[4] changed to 10 using sliced variable a. 

array([ 2,  0,  4,  5, 10,  8,  9])

In [35]:
array5=np.array([3,4,5,6,7,8,9])

In [36]:
array5

array([3, 4, 5, 6, 7, 8, 9])

In [37]:
a=array5[4:6].copy() # doesnt change the values in the parent cell

In [38]:
a

array([7, 8])

In [39]:
a[0]=0

In [40]:
a

array([0, 8])

In [41]:
array5 # cell value not changed

array([3, 4, 5, 6, 7, 8, 9])

In [42]:
a=array5[4:6] # will change the values of the parent cell at the referenced index

In [43]:
a[0]=0

In [44]:
a

array([0, 8])

In [45]:
array5 # cell value changed

array([3, 4, 5, 6, 0, 8, 9])

In [46]:
a= array5[:7]

In [47]:
a

array([3, 4, 5, 6, 0, 8, 9])

In [48]:
a= array5[:]

In [49]:
a

array([3, 4, 5, 6, 0, 8, 9])

In [50]:
a= array5[0:]

In [51]:
a

array([3, 4, 5, 6, 0, 8, 9])

In [52]:
a= array5[:-3]

In [53]:
a

array([3, 4, 5, 6])

In [54]:
a= array5[-3:]

In [55]:
a

array([0, 8, 9])