In [1]:
import numpy as np

In [2]:
a= np.arange(6)

In [3]:
a

array([0, 1, 2, 3, 4, 5])

In [43]:
b= np.array([1,23,34,34,34,4,5,6,3,7,34,2,1,1,5,4,2,6])
# b.shape #  shows total no of elements: 18 here 
# b.reshape(6,3) # will modify the shape of array and print but wont assign it to b
# b.reshape(6,4) # will throw an error invalid dimensions 
b= b.reshape(6,3) # will modify the shape of array and print but will also assign it to b

In [44]:
b


array([[ 1, 23, 34],
       [34, 34,  4],
       [ 5,  6,  3],
       [ 7, 34,  2],
       [ 1,  1,  5],
       [ 4,  2,  6]])

In [45]:
# np.argsort(b) # returns the index of the elemnts in b in ascending order. same as row wise axis=1.
np.argsort(b,axis=1) # ascending order of index row wise.

array([[0, 1, 2],
       [2, 0, 1],
       [2, 0, 1],
       [2, 0, 1],
       [0, 1, 2],
       [1, 0, 2]], dtype=int64)

In [46]:
np.argsort(b,axis=0) # ascending order of index coloumn wise.

array([[0, 4, 3],
       [4, 5, 2],
       [5, 2, 1],
       [2, 0, 4],
       [3, 1, 5],
       [1, 3, 0]], dtype=int64)

In [47]:
np.argmin(b) # returns the index of the minimum element of b

0

In [48]:
np.argmax(b) # returns the index of max element of b.

2