# Array creation : Conversion from other python structures.
array, dtype, shape, size, object

In [1]:
import numpy as np
array1=np.array([[2,0,4,5,6],[4,5,6,0,12]])

In [2]:
array1[0,4]

6

In [3]:
array1[0,4]=45

In [4]:
array1

array([[ 2,  0,  4,  5, 45],
       [ 4,  5,  6,  0, 12]])

In [5]:
listarray = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [6]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
listarray.dtype

dtype('int32')

In [8]:
listarray.shape

(3, 3)

In [9]:
listarray.size

9

In [10]:
np.array({1,2,3,3,3})

array({1, 2, 3}, dtype=object)

# Intrinsic numpy array creation
zeros, dtype, arange, linspace, empty, empty_like, identity, shape, reshape, ravel,

In [11]:
zeros= np.zeros((2,3))

In [12]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
zeros.dtype

dtype('float64')

In [14]:
range= np.arange(30)

In [15]:
range

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [16]:
linearspace= np.linspace(1,5,12) # returns 1 to 5 equally spaced 12 number of elemnts

In [17]:
linearspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [18]:
linearspace= np.linspace(1,4,3)

In [19]:
linearspace

array([1. , 2.5, 4. ])

In [20]:
emp = np.empty((4,6)) # returns random elements for the said array dimensions

In [21]:
emp

array([[4.67296746e-307, 1.69121096e-306, 3.11522054e-307,
        1.33511018e-306, 1.33511969e-306, 6.23037996e-307],
       [6.23053954e-307, 9.34609790e-307, 8.45593934e-307,
        9.34600963e-307, 1.86921143e-306, 6.23061763e-307],
       [8.90104239e-307, 6.89804132e-307, 9.34605716e-307,
        1.37962456e-306, 1.42418172e-306, 2.04712906e-306],
       [7.56589622e-307, 1.11258277e-307, 8.90111708e-307,
        2.11389826e-307, 1.11260619e-306, 5.08887615e-322]])

In [22]:
emp_like= np.empty_like(linearspace) # returns the random elements for the size equal to the argument.

In [23]:
emp_like

array([7.74860419e-304, 7.74860419e-304, 7.74860419e-304])

In [24]:
ide= np.identity(10) # returns identity matrix for the given dimensions

In [25]:
ide

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [26]:
np.shape(ide) # finding shape of the array method 1

(10, 10)

In [27]:
ide.shape # finding shape of the array method 2

(10, 10)

In [28]:
arr= np.arange(33) # returns array (n-1)

In [29]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32])

In [30]:
arr.reshape(3,11) # reshapes array to (rows,column)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32]])

In [31]:
arr # array doesnt get affected as variable is not assigned

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32])

In [32]:
arr= arr.reshape(3,11) # assigning variable to array

In [33]:
arr # array changes on assigning the variable

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32]])

In [34]:
arr.ravel() # converts the multiple arrays into a single array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32])

In [35]:
arr # array doesnt change variable not assigned

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32]])

In [36]:
arr= arr.ravel() # assigning variable

In [37]:
arr # values updated

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32])

In [38]:
arr.shape

(33,)

# Axis= 0 and Axis=1
ndim, flat, T, nbytes 
To remember - 
If bracket is there it means we are using the functions 
If bracket not there we are using an attribute


In [39]:
x= [[1,2,3],[4,5,6,], [7,8,9]]

In [40]:
ar= np.array(x)

In [41]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
ar.sum() # adding all the elements in the array

45

In [43]:
ar.sum(axis=0) # adds all the elements of columns

array([12, 15, 18])

In [44]:
ar.sum(axis=1) # adds all the elements of rows

array([ 6, 15, 24])

In [45]:
ar # array not changed as variable not assigned

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
ar.T # Transposing the array

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [47]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
ar.flat

In [49]:
for i in ar.flat:  # prints every element in the array
    print (i) 

1
2
3
4
5
6
7
8
9


In [50]:
ar.ndim # returns the dimension of the array in this case 2. Check the next case.

2

Example of 3d Array

In [51]:
ar1 = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[11,12,13],[14,15,16],[17,18,19]]])

In [52]:
ar1[1,0,1]

12

In [53]:
ar1.ndim # This is an example of a three dimensional array.

3

In [54]:
ar1.size # returns the total number of elements in the array

18

In [55]:
ar1.nbytes 
# total number of bytes consumed by array.Array size is 18. Bytes consumed is 72. 
#It may be a linked list. 
#Not sure check later.

72

In [56]:
ar.nbytes 
# total number of bytes consumed by array.Array size is 9. Bytes consumed is 36. 
#As each element consuems two bytes it may be a linked list with pointers pointing to some other nodes.
# Verify later.

36

# Argmax functions for 1 d arrays

In [57]:
one= np.array([4,5,6,23,0])

In [58]:
one.argmax() # returns the index of the largest element

3

In [59]:
one.argmin() # returns the index of the smallest element

4

In [60]:
one.argsort() 
# returns the index number of the sorted array.Remember it sorts the array first and then returns the index.Not to get confused.

array([4, 0, 1, 2, 3], dtype=int64)

In [61]:
one

array([ 4,  5,  6, 23,  0])

#  2 d arrays
Argmax Argmin Argsort ravel functions
*Note - Arg always returns index and not the number.

In [62]:
x= [[1,2,3],[4,5,6], [7,8,9]]

In [63]:
ar= np.array(x)

In [64]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [65]:
ar.argmax() # returns the index of the largest elemnt

8

In [66]:
ar.argmin()  # returns the index of the smallest elemnt

0

In [67]:
ar.argmax(axis=0) # returns the index of the largest element coloumn wise. Here 7,8,9

array([2, 2, 2], dtype=int64)

In [68]:
ar.argmax(axis=1) # returns the index of the largest element row wise. Here 3,6,9

array([2, 2, 2], dtype=int64)

In [69]:
ar.argmin(axis=0) # returns the index of the smallest element coloumn wise

array([0, 0, 0], dtype=int64)

In [70]:
ar.argmin(axis=1) # returns the index of the smallest element row wise

array([0, 0, 0], dtype=int64)

In [71]:
ar.argsort() # same as axis=1

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [72]:
ar.argsort(axis = 0)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]], dtype=int64)

In [73]:
ar.argsort(axis=1) # same as axis=1

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [74]:
ar.ravel  # message box says it is a function .dont forget to add the brackets () :)

<function ndarray.ravel>

In [75]:
ar.ravel () #  2D array sorted to a 1D array 

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
ar.reshape(9,1) # reshaped to 1 row 9 coloumns

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [77]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [78]:
ar1= np.array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [79]:
ar1

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [80]:
ar + ar1 # numpy arrays enables us to do matrix operation while python list doesn't.Check next cell.

array([[12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [81]:
[1,2,3] + [11,12,13] # Python simply joins the two list but doesnt perform an arithematic operation.

[1, 2, 3, 11, 12, 13]

In [82]:
ar * ar1

array([[ 11,  24,  39],
       [ 56,  75,  96],
       [119, 144, 171]])

In [83]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [84]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [85]:
ar.sum() # adds all the elements in the array

45

In [86]:
ar.max() # returns max element in the array

9

In [87]:
ar.min()  # returns min element in the array

1

# Finding the number in the array - Condition based 
count, where, count_nonzero

In [88]:
y= [[1,2,3],[4,5,6], [1,2,3]]

In [89]:
ar= np.array(y)

In [90]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]])

In [91]:
type(np.where(ar==5))

tuple

In [92]:
np.where(ar==5) # finding the index of the particular element in the array.

(array([1], dtype=int64), array([1], dtype=int64))

In [93]:
np.where(ar>5) # finding the index of the particular element in the array.here 6 located at (1,2) index.

(array([1], dtype=int64), array([2], dtype=int64))

In [94]:
np.where(ar>3) # finding the index of the particular element in the array.here 4,5,6 located at (1,0) (1,1) (1,2) index respec.

(array([1, 1, 1], dtype=int64), array([0, 1, 2], dtype=int64))

In [95]:
np.count_nonzero(ar) # counts the non zero elements

9

In [96]:
np.nonzero(ar)  # returns the tuple with index of the non zero elements. 9 elements returned. (0,0)corresponds to 1,(0,1)corresponds to 2 and so on. 

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [97]:
ar[1,1]= 0 # cahnging the element at 1,1 to 0 for checking

In [98]:
ar # (1,1) changed to 0

array([[1, 2, 3],
       [4, 0, 6],
       [1, 2, 3]])

In [99]:
np.nonzero(ar) # returns the tuple with index of the non zero elements. 8 elements returned as (1,1) was changed to 0.

(array([0, 0, 0, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 2, 0, 1, 2], dtype=int64))

In [100]:
ar

array([[1, 2, 3],
       [4, 0, 6],
       [1, 2, 3]])

In [101]:
ar.argsort(axis=0)

array([[0, 1, 0],
       [2, 0, 2],
       [1, 2, 1]], dtype=int64)

In [102]:
ar.argsort()

array([[0, 1, 2],
       [1, 0, 2],
       [0, 1, 2]], dtype=int64)

In [103]:
ar.ravel()

array([1, 2, 3, 4, 0, 6, 1, 2, 3])

In [104]:
ar

array([[1, 2, 3],
       [4, 0, 6],
       [1, 2, 3]])

In [105]:
ar= ar.ravel()

In [106]:
ar

array([1, 2, 3, 4, 0, 6, 1, 2, 3])

In [107]:
ar.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [0],
       [6],
       [1],
       [2],
       [3]])

In [108]:
ar

array([1, 2, 3, 4, 0, 6, 1, 2, 3])

In [109]:
ar= ar.reshape(9,1)

In [110]:
ar

array([[1],
       [2],
       [3],
       [4],
       [0],
       [6],
       [1],
       [2],
       [3]])

# Matrix arithematic operations with numpy 


In [111]:
ar= np.array([[1,2,3],[4,5,6], [7,1,0]])

In [112]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [113]:
ar2= np.array([[1,2,1],[4,0,6], [8,1,0]])

In [114]:
ar2

array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [115]:
ar+ar2 # arithematic operations can be used with matrice in numpy while in python list it doesnt allow. refer next cell

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [116]:
[1,2,3] + [4,5,6,] # doesnt add the numbers but joins the two list in python. Numpy performs arithematic operations.


[1, 2, 3, 4, 5, 6]

In [117]:
ar * ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [118]:
# [1,2,3] * [4,5,6,] # python doesnt allow multiplication of lists.

In [119]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

# Numpy's space occupancy

In [120]:
py_list= [45,56,87,98] # creating a python list

In [121]:
np_list = np.array(py_list) # creating a numpy array

In [122]:
import sys

In [123]:
sys.getsizeof(0) # python consumes 24 bit for storing zero 

24

In [124]:
sys.getsizeof(1) # python consumes 28 bit for storing one, two threes etc

28

In [125]:
sys.getsizeof(2)

28

In [126]:
sys.getsizeof(3)

28

In [127]:
sys.getsizeof(4)

28

In [128]:
sys.getsizeof(5)

28

In [129]:
sys.getsizeof(10)

28

In [130]:
sys.getsizeof(100)

28

In [131]:
sys.getsizeof(9999)

28

In [132]:
sys.getsizeof(9999999999999999999)

36

In [133]:
sys.getsizeof(99999999999999999999999999999999999999999999999)

48

In [134]:
sys.getsizeof(999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999)

72

In [135]:
sys.getsizeof(99999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999)

148

In [136]:
py_list

[45, 56, 87, 98]

In [137]:
len(py_list)

4

In [138]:
sys.getsizeof(1)* len(py_list)  # to find the space consumed by the list in python. 28 x 4 = 112. 28 bit is the size of 1 element. 

112

In [139]:
np_list.itemsize* np_list.size # Space consumed by numpy is just 16 bytes for 4 elements.

16

In [140]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [141]:
ar.tolist() # converts numpy array to python list. 

[[1, 2, 3], [4, 5, 6], [7, 1, 0]]

# Practice slicing using newaxis


In [142]:
import numpy as np
x= np.array([[1,2,3,4,5,6,7,8],[11,12,13,14,15,16,17,18],[21,22,23,24,25,26,27,28]])

In [143]:
a= x[1:3,np.newaxis,1] 

In [144]:
b= x[np.newaxis,1:3,1:7] # have a look on brackets. Here 3 dimensional array in form of columns array is created 

In [145]:
c= x[1:3,np.newaxis,1:7] # have a look on brackets. Here 3 dimensional array in form of row array is created 

In [146]:
a

array([[12],
       [22]])

In [147]:
b

array([[[12, 13, 14, 15, 16, 17],
        [22, 23, 24, 25, 26, 27]]])

In [148]:
c

array([[[12, 13, 14, 15, 16, 17]],

       [[22, 23, 24, 25, 26, 27]]])

In [149]:
a.shape # it has 2 row 1 column

(2, 1)

In [150]:
b.shape # it has only 1 row 2 columns and having 6 elements in each column which is the third dimension

(1, 2, 6)

In [151]:
c.shape # it has 2 rows and only 1 column with 6 elements in each of the row which is the third dimension

(2, 1, 6)

In [152]:
y= np.array([1,2,3,4,5,6,7,8])

In [153]:
y[:]

array([1, 2, 3, 4, 5, 6, 7, 8])

In [154]:
y[-2:]

array([7, 8])

In [155]:
y[:-2]

array([1, 2, 3, 4, 5, 6])

In [156]:
b[0]

array([[12, 13, 14, 15, 16, 17],
       [22, 23, 24, 25, 26, 27]])

In [157]:
c[0]

array([[12, 13, 14, 15, 16, 17]])

# Some More Practice example on reshaping 

In [158]:
import numpy as np
x= np.array([[1,2,3,4,5,6,7,8],[11,12,13,14,15,16,17,18],[21,22,23,24,25,26,27,28]])


In [159]:
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [11, 12, 13, 14, 15, 16, 17, 18],
       [21, 22, 23, 24, 25, 26, 27, 28]])

In [160]:
x.shape

(3, 8)

In [161]:
x.reshape(1,24)

array([[ 1,  2,  3,  4,  5,  6,  7,  8, 11, 12, 13, 14, 15, 16, 17, 18,
        21, 22, 23, 24, 25, 26, 27, 28]])

In [162]:
x.reshape(24,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [21],
       [22],
       [23],
       [24],
       [25],
       [26],
       [27],
       [28]])

In [163]:
x.reshape(3,-10000)

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [11, 12, 13, 14, 15, 16, 17, 18],
       [21, 22, 23, 24, 25, 26, 27, 28]])

In [164]:
import numpy as np
x= np.array([[11,12,13,14,15,16,17,18],[21,22,23,24,25,26,27,28],[1,2,3,4,5,6,7,8]])
x

array([[11, 12, 13, 14, 15, 16, 17, 18],
       [21, 22, 23, 24, 25, 26, 27, 28],
       [ 1,  2,  3,  4,  5,  6,  7,  8]])

In [165]:
x =x.ravel()

In [166]:
x

array([11, 12, 13, 14, 15, 16, 17, 18, 21, 22, 23, 24, 25, 26, 27, 28,  1,
        2,  3,  4,  5,  6,  7,  8])

In [167]:
x.argsort()

array([16, 17, 18, 19, 20, 21, 22, 23,  0,  1,  2,  3,  4,  5,  6,  7,  8,
        9, 10, 11, 12, 13, 14, 15], dtype=int64)

In [168]:
ar = np.array([[1,2,3],[4,5,6],[7,1,0]])
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [169]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [170]:
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int64)

In [171]:
ar = np.array([[18,2,3],[4,15,6],[17,2,23]])
ar

array([[18,  2,  3],
       [ 4, 15,  6],
       [17,  2, 23]])

In [172]:
ar.argsort(axis=0)

array([[1, 0, 0],
       [2, 2, 1],
       [0, 1, 2]], dtype=int64)

In [173]:
ar

array([[18,  2,  3],
       [ 4, 15,  6],
       [17,  2, 23]])

In [174]:
ar[:]

array([[18,  2,  3],
       [ 4, 15,  6],
       [17,  2, 23]])

In [175]:
ar[[0,1],:]

array([[18,  2,  3],
       [ 4, 15,  6]])

In [182]:
ar

array([[18,  2,  3],
       [ 4, 15,  6],
       [17,  2, 23]])

In [181]:
ar[[0,1,2,0],[0,1,2,2]]

array([18, 15, 23,  3])

In [177]:
ar[1:2,2]

array([6])

__Transposing 3d Matrices/ 3d matrix__ 

In [7]:
import numpy as np
arr = np.arange(24).reshape(2,3,4)

In [8]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [9]:
arr.shape

(2, 3, 4)

In [10]:
arr.T.shape

(4, 3, 2)

In [11]:
arr.T

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

__4d transpose__

In [12]:
import numpy as np
arr = np.arange(120).reshape(2,3,4,5)

In [13]:
arr

array([[[[  0,   1,   2,   3,   4],
         [  5,   6,   7,   8,   9],
         [ 10,  11,  12,  13,  14],
         [ 15,  16,  17,  18,  19]],

        [[ 20,  21,  22,  23,  24],
         [ 25,  26,  27,  28,  29],
         [ 30,  31,  32,  33,  34],
         [ 35,  36,  37,  38,  39]],

        [[ 40,  41,  42,  43,  44],
         [ 45,  46,  47,  48,  49],
         [ 50,  51,  52,  53,  54],
         [ 55,  56,  57,  58,  59]]],


       [[[ 60,  61,  62,  63,  64],
         [ 65,  66,  67,  68,  69],
         [ 70,  71,  72,  73,  74],
         [ 75,  76,  77,  78,  79]],

        [[ 80,  81,  82,  83,  84],
         [ 85,  86,  87,  88,  89],
         [ 90,  91,  92,  93,  94],
         [ 95,  96,  97,  98,  99]],

        [[100, 101, 102, 103, 104],
         [105, 106, 107, 108, 109],
         [110, 111, 112, 113, 114],
         [115, 116, 117, 118, 119]]]])

In [14]:
arr.shape

(2, 3, 4, 5)

In [15]:
arr.T.shape

(5, 4, 3, 2)

In [16]:
arr.T

array([[[[  0,  60],
         [ 20,  80],
         [ 40, 100]],

        [[  5,  65],
         [ 25,  85],
         [ 45, 105]],

        [[ 10,  70],
         [ 30,  90],
         [ 50, 110]],

        [[ 15,  75],
         [ 35,  95],
         [ 55, 115]]],


       [[[  1,  61],
         [ 21,  81],
         [ 41, 101]],

        [[  6,  66],
         [ 26,  86],
         [ 46, 106]],

        [[ 11,  71],
         [ 31,  91],
         [ 51, 111]],

        [[ 16,  76],
         [ 36,  96],
         [ 56, 116]]],


       [[[  2,  62],
         [ 22,  82],
         [ 42, 102]],

        [[  7,  67],
         [ 27,  87],
         [ 47, 107]],

        [[ 12,  72],
         [ 32,  92],
         [ 52, 112]],

        [[ 17,  77],
         [ 37,  97],
         [ 57, 117]]],


       [[[  3,  63],
         [ 23,  83],
         [ 43, 103]],

        [[  8,  68],
         [ 28,  88],
         [ 48, 108]],

        [[ 13,  73],
         [ 33,  93],
         [ 53, 113]],

        [[ 18,  78]